# This file exists on purpose as long as this is a template repository.
# This file will be deleted once it's a repository created from a template repository (hence: no longer template).
# Don't worry, we have one of Github Actions automatically taking care of it.
# So, humans - just relax and focus on someting more important!